//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Kullanici_ID { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Kullanici_Parola { get; set; }
        public string Kullanici_Email { get; set; }
        public Nullable<int> Rol_ID { get; set; }
        public Nullable<System.DateTime> Kayıt_Tarihi { get; set; }
        public Nullable<System.DateTime> Son_Giris_Tarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
