//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorular()
        {
            this.Secenekler = new HashSet<Secenekler>();
            this.Yanitlar = new HashSet<Yanitlar>();
        }
    
        public int Soru_ID { get; set; }
        public Nullable<int> Anket_ID { get; set; }
        public string Soru_Baslik { get; set; }
        public Nullable<int> Soru_Tipi { get; set; }
        public Nullable<bool> Soru_Durum { get; set; }
        public Nullable<System.DateTime> Soru_Olusturma_Tarih { get; set; }
        public Nullable<System.DateTime> Soru_Guncelle_Tarih { get; set; }
    
        public virtual Anketler Anketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secenekler> Secenekler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yanitlar> Yanitlar { get; set; }
    }
}
